/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/czz/movian-go/cmd/movian-go */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 13 "android_jni.go"


#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static const char *
ml_jni_getstr(JNIEnv *env, jstring s)
{
  return s == NULL ? NULL : (*env)->GetStringUTFChars(env, s, 0);
}

static void
ml_jni_relstr(JNIEnv *env, jstring s, const char *c)
{
  if(s != NULL && c != NULL)
    (*env)->ReleaseStringUTFChars(env, s, c);
}

static jclass
ml_jni_find_class(JNIEnv *env, const char *name)
{
  return (*env)->FindClass(env, name);
}

static jobject
ml_jni_new_global_ref(JNIEnv *env, jobject o)
{
  return (*env)->NewGlobalRef(env, o);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jint JNI_OnLoad(JavaVM* vm, void* reserved);
extern void Java_com_moviango_mediaplayer_Core_coreInit(JNIEnv* env, jobject obj, jstring jSettings, jstring jCachedir, jstring jSdcard, jstring jAndroidID, jint time24hrs, jstring jMusic, jstring jPictures, jstring jMovies, jint audioSampleRate, jint audioFramesPerBuffer);
extern void Java_com_moviango_mediaplayer_Core_openUri(JNIEnv* env, jobject obj, jstring jURI);
extern void Java_com_moviango_mediaplayer_Core_networkStatusChanged(JNIEnv* env, jobject obj);
extern void Java_com_moviango_mediaplayer_Core_permissionResult(JNIEnv* env, jobject obj, jboolean ok);
extern jint Java_com_moviango_mediaplayer_Core_glwCreate(JNIEnv* env, jobject obj, jobject vrp);
extern void Java_com_moviango_mediaplayer_Core_glwInit(JNIEnv* env, jobject obj, jint id);
extern void Java_com_moviango_mediaplayer_Core_glwFini(JNIEnv* env, jobject obj, jint id);
extern void Java_com_moviango_mediaplayer_Core_glwDestroy(JNIEnv* env, jobject obj, jint id);
extern void Java_com_moviango_mediaplayer_Core_glwResize(JNIEnv* env, jobject obj, jint id, jint width, jint height);
extern void Java_com_moviango_mediaplayer_Core_glwFlush(JNIEnv* env, jobject obj, jint id);
extern void Java_com_moviango_mediaplayer_Core_glwStep(JNIEnv* env, jobject obj, jint id);
extern void Java_com_moviango_mediaplayer_Core_glwMotion(JNIEnv* env, jobject obj, jint id, jint source, jint action, jint x, jint y, jlong ts);
extern jboolean Java_com_moviango_mediaplayer_Core_glwKeyDown(JNIEnv* env, jobject obj, jint id, jint keycode, jint unicode, jboolean shift);
extern jboolean Java_com_moviango_mediaplayer_Core_glwKeyUp(JNIEnv* env, jobject obj, jint id, jint keycode);
extern jint Java_com_moviango_mediaplayer_Core_vdInputAvailable(JNIEnv* env, jobject obj, jint jopaque, jint jbuf);
extern jint Java_com_moviango_mediaplayer_Core_vdOutputAvailable(JNIEnv* env, jobject obj, jint jopaque, jint jbuf, jlong pts);
extern jint Java_com_moviango_mediaplayer_Core_vdOutputFormatChanged(JNIEnv* env, jobject obj, jint jopaque, jobject jinfo);
extern jint Java_com_moviango_mediaplayer_Core_vdError(JNIEnv* env, jobject obj, jint jopaque);

#ifdef __cplusplus
}
#endif
