//go:build ignore

package main

import (
	"fmt"
	"os"
)

// Regenerates cgo_directives.go — the canonical FFmpeg cgo directives
// for pkg/media/libav. All paths are ${SRCDIR}-relative so the file is
// checkout-location independent; pkg/media/libav sits three levels
// below the repo root (../../../ffmpeg).
//
// The output is tracked in git: `go run generate_cgo.go` followed by
// `git diff --exit-code cgo_directives.go` is the drift check.
func main() {
	content := `// Code generated by go generate; DO NOT EDIT.
package libav

/*
#cgo linux,!android,!arm CFLAGS: -I${SRCDIR}/../../../ffmpeg/include
#cgo linux,arm,!android CFLAGS: -I${SRCDIR}/../../../ffmpeg/rpi/include
#cgo darwin,arm64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/darwin/arm64/include
#cgo darwin,amd64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/darwin/amd64/include
#cgo android,arm64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/android/arm64/include
#cgo android,arm CFLAGS: -I${SRCDIR}/../../../ffmpeg/android/arm/include
#cgo linux,!android,!arm LDFLAGS: -L${SRCDIR}/../../../ffmpeg/lib -Wl,--start-group -lavcodec -lavformat -lavutil -lswresample -lswscale -Wl,--end-group -lm -lpthread -lz -lbz2 -llzma -lxml2 -lva -lva-drm -ldrm
#cgo linux,arm,!android LDFLAGS: -L${SRCDIR}/../../../ffmpeg/rpi/lib -Wl,--start-group -lavcodec -lavformat -lavutil -lswresample -lswscale -Wl,--end-group -lm -lpthread -lz -lbz2 -llzma -lxml2
#cgo darwin,arm64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/darwin/arm64/lib
#cgo darwin,amd64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/darwin/amd64/lib
#cgo darwin LDFLAGS: -lavcodec -lavformat -lavutil -lswresample -lswscale -lm -lz -lbz2 -liconv
#cgo windows,amd64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/windows/amd64/include
#cgo windows,386 CFLAGS: -I${SRCDIR}/../../../ffmpeg/windows/386/include
#cgo windows,amd64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/windows/amd64/lib -L${SRCDIR}/../../../third_party/zlib/windows/amd64/lib -L${SRCDIR}/../../../third_party/libxml2/windows/amd64/lib -lavcodec -lavformat -lavutil -lswresample -lswscale -lm -lz -lxml2 -lws2_32 -lbcrypt -lsecur32 -lole32 -luuid -ld3d11 -ldxgi -ld3d9 -lncrypt -lcrypt32 -lwinmm
#cgo windows,386 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/windows/386/lib -L${SRCDIR}/../../../third_party/zlib/windows/386/lib -L${SRCDIR}/../../../third_party/libxml2/windows/386/lib -lavcodec -lavformat -lavutil -lswresample -lswscale -lm -lz -lxml2 -lws2_32 -lbcrypt -lsecur32 -lole32 -luuid -ld3d11 -ldxgi -ld3d9 -lncrypt -lcrypt32 -lwinmm
#cgo android,arm64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/android/arm64/lib -L${SRCDIR}/../../../third_party/libxml2/android/arm64/lib -Wl,--start-group -lavcodec -lavformat -lavutil -lswresample -lswscale -Wl,--end-group -lm -lz -lxml2 -ldl -llog -landroid -lmediandk
#cgo android,arm LDFLAGS: -L${SRCDIR}/../../../ffmpeg/android/arm/lib -L${SRCDIR}/../../../third_party/libxml2/android/arm/lib -Wl,--start-group -lavcodec -lavformat -lavutil -lswresample -lswscale -Wl,--end-group -lm -lz -lxml2 -ldl -llog -landroid -lmediandk
*/
import "C"
`

	if err := os.WriteFile("cgo_directives.go", []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing cgo_directives.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated cgo_directives.go (${SRCDIR}-relative)")
}
