//go:build ignore

package main

import (
	"fmt"
	"os"
)

// Regenerates screenshot_cgo.go — canonical FFmpeg cgo directives for
// pkg/api/screenshot (${SRCDIR}-relative; the package sits three levels
// below the repo root → ../../../ffmpeg).
// Tracked in git — drift check: `go run generate_screenshot_cgo.go`
// then `git diff --exit-code screenshot_cgo.go`.
func main() {
	content := `// Code generated by go generate; DO NOT EDIT.
package screenshot

/*
#cgo linux,!android,!arm CFLAGS: -I${SRCDIR}/../../../ffmpeg/include
#cgo linux,arm,!android CFLAGS: -I${SRCDIR}/../../../ffmpeg/rpi/include
#cgo android,arm64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/android/arm64/include
#cgo android,arm CFLAGS: -I${SRCDIR}/../../../ffmpeg/android/arm/include
#cgo linux,!android,!arm LDFLAGS: -L${SRCDIR}/../../../ffmpeg/lib -Wl,--start-group -lavcodec -lavutil -lswscale -Wl,--end-group -lm -lz -lpthread -lbz2 -llzma -lva -lva-drm -ldrm
#cgo linux,arm,!android LDFLAGS: -L${SRCDIR}/../../../ffmpeg/rpi/lib -Wl,--start-group -lavcodec -lavutil -lswscale -Wl,--end-group -lm -lz -lpthread -lbz2
#cgo android,arm64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/android/arm64/lib -Wl,--start-group -lavcodec -lavutil -lswscale -Wl,--end-group -lm -lz -ldl -llog -landroid -lmediandk
#cgo android,arm LDFLAGS: -L${SRCDIR}/../../../ffmpeg/android/arm/lib -Wl,--start-group -lavcodec -lavutil -lswscale -Wl,--end-group -lm -lz -ldl -llog -landroid -lmediandk
#cgo darwin,arm64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/darwin/arm64/include
#cgo darwin,amd64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/darwin/amd64/include
#cgo darwin,arm64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/darwin/arm64/lib
#cgo darwin,amd64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/darwin/amd64/lib
#cgo darwin LDFLAGS: -lavcodec -lavformat -lavutil -lswresample -lswscale -lm -lz -lbz2 -liconv
#cgo windows,amd64 CFLAGS: -I${SRCDIR}/../../../ffmpeg/windows/amd64/include
#cgo windows,386 CFLAGS: -I${SRCDIR}/../../../ffmpeg/windows/386/include
#cgo windows,amd64 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/windows/amd64/lib -L${SRCDIR}/../../../third_party/zlib/windows/amd64/lib -L${SRCDIR}/../../../third_party/libxml2/windows/amd64/lib -lavcodec -lavutil -lswscale -lm -lz -lxml2 -lws2_32 -lbcrypt -lsecur32 -lole32 -luuid -ld3d11 -ldxgi -ld3d9
#cgo windows,386 LDFLAGS: -L${SRCDIR}/../../../ffmpeg/windows/386/lib -L${SRCDIR}/../../../third_party/zlib/windows/386/lib -L${SRCDIR}/../../../third_party/libxml2/windows/386/lib -lavcodec -lavutil -lswscale -lm -lz -lxml2 -lws2_32 -lbcrypt -lsecur32 -lole32 -luuid -ld3d11 -ldxgi -ld3d9
#include <libavcodec/avcodec.h>
#include <libavutil/pixfmt.h>
#include <libavutil/imgutils.h>
#include <libswscale/swscale.h>

#define AVCodecIDMjpeg 7
#define AVCodecIDPng 61
#define SwsBilinear 2
*/
import "C"
`

	if err := os.WriteFile("screenshot_cgo.go", []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing screenshot_cgo.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated screenshot_cgo.go (${SRCDIR}-relative)")
}
